remote: true

experienceLevel:
 internship: true
 entry: true
 associate: true
 mid-senior level: false
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: true
 temporary: false
 internship: true
 other: false
 volunteer: false

date:
 all time: true
 month: false
 week: false
 24 hours: false

positions:
  - DevOps Engineer
  - DevOps Consultant
  - DevOps Specialist
  - DevOps Architect
  - DevOps Lead
  - Build and Release Engineer
  - Automation Engineer
  - Infrastructure Engineer
  - Platform Engineer
  - Systems Engineer
  - Continuous Integration/Continuous Deployment (CI/CD) Engineer
  - Cloud Engineer
  - Cloud Architect
  - Cloud Consultant
  - Cloud Developer
  - Cloud Systems Administrator
  - Cloud Infrastructure Engineer
  - Cloud Solutions Architect
  - Cloud Services Developer
  - Cloud Security Engineer
  - Cloud Operations Engineer
  - Cloud Network Engineer
  - Cloud Software Engineer
  - Cloud Support Engineer
  - Cloud Systems Engineer
  - Backend Developer
  - Backend Engineer
  - Backend Software Engineer
  - Server-Side Developer
  - API Developer
  - Web Services Developer
  - Database Developer
  - Systems Integration Engineer
  - Data Engineer
  - Application Developer
  - Software Systems Engineer
  - Backend Systems Engineer
  - Backend Application Engineer
  - Backend Architect
  - Software Engineer
  - Software Developer
  - Software Architect
  - Software Engineer in Test (SDET)
  - Full Stack Developer
  - Application Developer
  - Systems Engineer
  - Software Design Engineer
  - Software Consultant
  - Technical Lead
  - Software Development Engineer (SDE)
  - Software Development Engineer in Test (SDET)
  - Software Quality Assurance Engineer
  - Software Support Engineer

locations:
  - Tampere
  - Helsinki
  - Espoo
  - Finland
  - Europe

distance: 100

# companyBlacklist:

# titleBlacklist:
